name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: true
  AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  SCCACHE_REGION: ${{ vars.SCCACHE_REGION }}
  SCCACHE_BUCKET: ${{ vars.SCCACHE_BUCKET }}
  SCCACHE_ENDPOINT: ${{ vars.SCCACHE_ENDPOINT }}
  SCCACHE_SERVER_PORT: ${{ vars.SCCACHE_SERVER_PORT }}
  SCCACHE_S3_USE_SSL: ${{ vars.SCCACHE_S3_USE_SSL }}
  RUSTC_WRAPPER: sccache

jobs:
  build-test-check-clippy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2

    - name: cache rust toolchain
      uses: actions/cache@v4.2.2
      with:
        path: |
          ~/.cargo
          ~/.rustup
        key: ${{ runner.os }}-rust

    - name: install rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy

    - name: setup rust cache
      uses: Swatinem/rust-cache@v2.7.7
      with:
        cache-all-crates: "true"

    - name: use sccache
      uses: mozilla-actions/sccache-action@v0.0.8
      with:
        version: "${{ vars.SCCACHE_VERSION }}"

    - name: run cargo build main
      run: cargo build --all --release

    - name: run cargo test
      run: cargo test

    - name: run cargo check
      run: cargo check

  format:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2

    - name: cache rust toolchain
      uses: actions/cache@v4.2.2
      with:
        path: |
          ~/.cargo
          ~/.rustup
        key: ${{ runner.os }}-rust

    - name: install latest rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt

    - name: format check
      run: cargo fmt -- --check

  conventional-commits:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2

    - name: conventional commits
      uses: webiny/action-conventional-commits@v1.3.0
