name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install rust
      uses: dtolnay/rust-toolchain@master
      with:
          toolchain: stable
    - uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: "true"
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -F bundled
